# .github/workflows/ci.yml
# This workflow runs tests and builds the project on pushes/PRs to the main branch.

name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Use LTS Node.js versions
        node-version: [18.x, 20.x]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Sets up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Enable caching for npm dependencies

    # Installs dependencies using 'npm ci' for faster, reliable installs
    - name: Install dependencies
      run: npm ci

    # Runs Vitest tests defined in your package.json ('npm run test')
    - name: Run tests
      run: npm run test --if-present

    # Builds the project using Vite ('npm run build')
    - name: Build project
      run: npm run build --if-present
